name: Deploy Laravel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        php artisan key:generate
    
    - name: Build assets
      run: |
        npm install
        npm run build

    - name: Upload via FTP - Laravel (fora do public)
      uses: samkirkland/ftp-deploy-action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_TARGET }}/barber-flow/
        local-dir: ./
        exclude: |
          **/vendor/**
          **/node_modules/**
          **/.git/**
          **/.github/**
          **/tests/**
          **/.env.example
    - name: Upload via FTP - public_html (apenas a pasta public)
      uses: samkirkland/ftp-deploy-action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_TARGET }}/public_html/
        local-dir: ./public/